spring:
  application:
  name: rest-fhir-to-kafka

  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      compression-type: gzip
      compression:
        gzip:
          level: 9
      retries: 3
      security:
        protocol: SSL
      client-id: test-rest-to-kafka
app:
  id-salt: "5fd7b89ace314e810e565e3827c11c23"
logging:
  level:
    root: "warn"

server:
  port: 8081