spring:
  application:
  name: rest-fhir-to-kafka

  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      compression-type: gzip
      compression:
        gzip:
          level: 9
      retries: 3
      security:
        protocol: PLAINTEXT
      client-id: test-rest-to-kafka

logging:
  level:
    root: "warn"
    de.unimarburg: "debug"